### ISSUE TITLE
servers Icons show Hoizontally

### ISSUE THREAD

**Issue by stranger118** [Eight-P/BetterDiscord-Stuff#6]
### T1 Issue report:

[![image](https://user-images.githubusercontent.com/93292002/139152768-4928f726-9172-4127-a54e-cd90eb0b6c50.png)](url)
as u can see this just happened randomly ..

### T1 version:

v0.5373 | 0.7.3

### Discord client:

Stable (Default)

### Platform:

Windows

### Discord Mod:

BetterDiscord

**Comment by Mickxz** [comment]
Issue happening again after updating BD

**Comment by Eight-P** [comment]
#8
